Repository lucasdotvin/laravel-soulbscription, pull requests merged in 2022-07, with the labels that each got.

#15 - Added uses_uuid to config file
  config/soulbscription.php
Labels: bug, documentation

#13 Update 2022_02_01_235539_create_subscriptions_table.php
  database/migrations/2022_02_01_235539_create_subscriptions_table.php
  src/Models/Concerns/HasSubscriptions.php
Labels: bug

#19 Added documentation for fetching remaining charges
  README.md
Labels: documentation
